CREATE SCHEMA IF NOT EXISTS transfert_money;

SET search_path TO transfert_money;

CREATE TABLE IF NOT EXISTS users
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,    
    created_by  VARCHAR(255)                            NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by  VARCHAR(255)                             NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);