server:
  port: 8089

spring:    
    application:
        name: springboot
    datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DATABASE_URL:jdbc:postgresql://pg-21236294-akouayao2017-1f4d.f.aivencloud.com:25431/defaultdb}
      username: ${DATABASE_USERNAM:avnadmin}
      password: ${DATABASE_PASSWORD:AVNS_CPiFeFEWHbLX4LGFYzW}
    