server:
  port: 8089

spring:    
    application:
        name: springboot
    datasource:
      driver-class-name: org.postgresql.Driver
      #Without schema
      url: ${DATABASE_URL:jdbc:postgresql://pg-21236294-akouayao2017-1f4d.f.aivencloud.com:25431/defaultdb}      
      username: ${DATABASE_USERNAM:avnadmin}
      password: ${DATABASE_PASSWORD:AVNS_CPiFeFEWHbLX4LGFYzW}      
  
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect      
      #With schema
      properties:
        hibernate:
          default_schema: ${DATASOURCE_DEFAULT_SCHEMA:transfert_money}
      
    flyway:
      schemas:
      - ${DATASOURCE_DEFAULT_SCHEMA:transfert_money}
      out-of-order: false

springdoc:
  swagger-ui:
    enabled: true
    disableSwaggerDefaultUrl: true
    #  showLoginEndpoint: false
    path: /swagger-ui.html
  apiDocs:
    path: /v3/api-docs
    