CREATE TABLE IF NOT EXISTS transaction(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_identifier    TEXT   NOT NULL,   
    transaction_type    VARCHAR(255)                    NOT NULL,
    description    TEXT                            NOT NULL,
    amount    DOUBLE PRECISION                          NOT NULL,
    created_by  VARCHAR(255)                            NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by  VARCHAR(255)                             NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    CONSTRAINT label_transaction_uc UNIQUE (transaction_identifier)
);