CREATE TABLE IF NOT EXISTS address(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label    TEXT                                           NOT NULL,   
    created_by  VARCHAR(255)                            NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by  VARCHAR(255)                             NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id),
    CONSTRAINT label_account_uc UNIQUE (label)
);