CREATE TABLE IF NOT EXISTS account (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number    VARCHAR(255)                            NOT NULL,   
    balance    DOUBLE PRECISION                            NOT NULL, 
    created_by  VARCHAR(255)                            NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by  VARCHAR(255)                             NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT account_number_account_uc UNIQUE (account_number)
);